# Generated by Django 4.2.20 on 2025-06-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='trails',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
