# Generated by Django 4.2.20 on 2025-06-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('password1', models.CharField(max_length=50, verbose_name='password')),
                ('password2', models.CharField(max_length=50, verbose_name='Confirm your password')),
            ],
        ),
    ]
